name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    if: github.event.deployment_status.state == 'success'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup NODE 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Run init tests
        run: npm run test:unit

      - name: Run storybook tests
        run: npm run test:storybook
        env:
          TARGET_URL: "${{ github.event.deployment_status.target_url }}"
